---
- name: Delete  log folders from gluster vol | update
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /mnt/gluster/logs
  run_once: true
  ignore_errors: yes

- name: Register frontend commit id
  shell: "source /etc/profile && echo $FRONTEND_COMMIT_ID"
  args:
    executable: /bin/bash
  register: frontend_commit_id
  delegate_to: 127.0.0.1

- name: Register backend commit id
  shell: "source /etc/profile && echo $BACKEND_COMMIT_ID"
  args:
    executable: /bin/bash
  register: backend_commit_id
  delegate_to: 127.0.0.1

- name: Updating backend deployment manifests
  lineinfile:
      destfile: "{{ DOOSRA_VPC_MANIFEST }}/backend/deployment/{{ item.file }}.yaml"
      regexp: '^(.*){{ item.key }}: (.*)$'
      line: '\1{{ item.key }}: "{{ item.value  }}"'
      backrefs: yes
  with_items:
    - { key: image, value: "wancloudsinc/doosra-vpc-backend:{{ backend_commit_id.stdout }}", file: backend-emailworker-deployment }
    - { key: image, value: "wancloudsinc/doosra-vpc-backend:{{ backend_commit_id.stdout }}", file: backend-scheduler-deployment }
    - { key: image, value: "wancloudsinc/doosra-vpc-backend:{{ backend_commit_id.stdout }}", file: backend-web-deployment }
    - { key: image, value: "wancloudsinc/doosra-vpc-backend:{{ backend_commit_id.stdout }}", file: backend-worker-deployment }

- name: Updating Frontend deployment manifests
  lineinfile:
      destfile: "{{ DOOSRA_VPC_MANIFEST }}/frontend/deployment/{{ item.file }}.yaml"
      regexp: '^(.*){{ item.key }}: (.*)$'
      line: '\1{{ item.key }}: "{{ item.value  }}"'
      backrefs: yes
  with_items:
    - { key: image, value: "wancloudsinc/doosra-vpc-frontend:{{ frontend_commit_id.stdout }}", file: frontend-app-deployment }

- name: Create required dirs in gluster vol | update
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /mnt/gluster/logs/scheduler
    - /mnt/gluster/logs/email_worker
    - /mnt/gluster/logs/worker
    - /mnt/gluster/logs/web
  run_once: true
