---

- name: Create required dirs in gluster vol | update
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /mnt/gluster/logs/scheduler
    - /mnt/gluster/logs/email_worker
    - /mnt/gluster/logs/worker
    - /mnt/gluster/logs/web
  run_once: true

- name: Delete services and deployments
  command: "{{item}}"
  with_items:
   - kubectl -n doosra-vpc delete -f manifests/backend/config-maps
   - kubectl -n doosra-vpc delete -f manifests/frontend/deployment
   - kubectl -n doosra-vpc delete -f manifests/backend/deployment/backend-emailworker-deployment.yaml
   - kubectl -n doosra-vpc delete -f manifests/backend/deployment/backend-scheduler-deployment.yaml
   - kubectl -n doosra-vpc delete -f manifests/backend/deployment/backend-web-deployment.yaml
   - kubectl -n doosra-vpc delete -f manifests/backend/deployment/backend-worker-deployment.yaml

- name: perform rolling update
  command: "{{item}}"
  with_items:
   - kubectl -n doosra-vpc create -f manifests/backend/config-maps
   - kubectl -n doosra-vpc create -f manifests/frontend/deployment
   - kubectl -n doosra-vpc create -f manifests/backend/deployment/backend-emailworker-deployment.yaml
   - kubectl -n doosra-vpc create -f manifests/backend/deployment/backend-scheduler-deployment.yaml
   - kubectl -n doosra-vpc create -f manifests/backend/deployment/backend-web-deployment.yaml
   - kubectl -n doosra-vpc create -f manifests/backend/deployment/backend-worker-deployment.yaml
