---
- include: mysql_root_pw.yml

- name: debian | installing pre-reqs
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'apt-transport-https'
    - 'software-properties-common'
    - 'python-mysqldb'
    - 'rsync'

- name: debian | Adding MariaDB Repo Keys
  apt_key:
    keyserver: "{{ mariadb_debian_repo_keyserver }}"
    id: "0xcbcb082a1bb943db"
    state: "present"
  when: >
        ansible_distribution == "Debian" or
        (ansible_distribution == "Ubuntu" and
        ansible_distribution_version <= '14.04')

- name: debian | Adding MariaDB Repo Keys
  apt_key:
    keyserver: "{{ mariadb_debian_repo_keyserver }}"
    id: "0xF1656F24C74CD1D8"
    state: "present"
  when: >
        (ansible_distribution == "Ubuntu" and
        ansible_distribution_version >= '16.04')

- name: debian | Pinning MariaDB Repo
  template:
    src: "mariadb_repo.j2"
    dest: "/etc/apt/preferences.d/mariadb"

- name: debian | adding mariadb repo
  apt_repository:
    repo: "{{ mariadb_debian_repo }}"
    state: "present"

- name: debian | installing mariadb-galera packages
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'mariadb-server'
    # - 'galera-3'

- name: debian | configuring root my.cnf
  template:
    src: "root/my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: "root"
    group: "root"
    mode: "u=rw,g=,o="

- name: debian | adding debian-sys-maintenance permissions to mysql
  mysql_user:
    name: "debian-sys-maint"
    password: "{{ galera_deb_db_password }}"
    priv: "*.*:ALL,GRANT"
    state: "present"
