---
- name: mysql_root_pw | setting
  debconf:
    name: "mariadb-server-{{ mariadb_version }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "password"
  changed_when: false
  no_log: true
  with_items:
    - question: 'mysql-server/root_password'
      value: "{{ hostvars[groups['all'][0]]['mariadb_mysql_root_password'] }}"
    - question: 'mysql-server/root_password_again'
      value: "{{ hostvars[groups['all'][0]]['mariadb_mysql_root_password'] }}"
  when: ansible_os_family == "Debian"
