---
- include: mysql_root_pw.yml

- name: redhat | adding mariadb repo
  template:
    src: "etc/yum.repos.d/MariaDB.repo.j2"
    dest: "/etc/yum.repos.d/MariaDB.repo"
    owner: "root"
    group: "root"
  register: repo_added

- name: redhat | installing pre-reqs
  yum:
    name: "{{ item }}"
    state: "present"
    update_cache: yes
  with_items:
    - 'MySQL-python'
    - 'socat'
  when: >
        ansible_distribution != "Fedora"

- name: redhat | installing mariadb mysql
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'MariaDB-server'
    - 'galera'
  when: >
        ansible_distribution != "Fedora"

- name: redhat | installing mariadb mysql
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - 'MariaDB-server'
    - 'galera'
    - 'MySQL-python'
  when: >
        ansible_distribution == "Fedora"

- name: redhat | ensuring mariadb mysql is enabled on boot and started
  service:
    name: "mysql"
    state: "started"
    enabled: yes

- name: redhat | Configure SELinux to permissive mode for MYSQL
  command: "{{item}}"
  with_items:
   - semanage port -a -t mysqld_port_t -p tcp 4567
   - semanage port -a -t mysqld_port_t -p udp 4567
   - semanage port -a -t mysqld_port_t -p tcp 4568
   - semanage port -a -t mysqld_port_t -p tcp 4444
   - semanage permissive -a mysqld_t
  ignore_errors: yes
