apiVersion: v1
data:
  .dockercfg: eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhc3dhZHdjIiwicGFzc3dvcmQiOiJuZXRvcmNhZ2VudEB3YW5jbG91ZHMjbmV0b3JjIiwiZW1haWwiOiJhc3dhZEB3YW5jbG91ZHMubmV0IiwiYXV0aCI6IllYTjNZV1IzWXpwdVpYUnZjbU5oWjJWdWRFQjNZVzVqYkc5MVpITWpibVYwYjNKaiJ9fQ==
kind: Secret
metadata:
  creationTimestamp: 2018-01-02T09:48:18Z
  name: docker-hub-secret
  namespace: doosra-vpc
  resourceVersion: "1863026"
  selfLink: /api/v1/namespaces/doosra-vpc/secrets/docker-hub-secret
  uid: 0fc221e0-efa2-11e7-b806-6248ff66fd54
type: kubernetes.io/dockercfg
