apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: doosra-vpc
  labels:
    app: rabbitmq
    type: LoadBalancer
spec:
  ports:
  - name: http
    protocol: TCP
    port: 15672
    targetPort: 15672
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
  clusterIP: None
