---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
  namespace: doosra-vpc
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: db
  selector:
    name: nginx
---
