---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: doosra-vpc
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name:  redis
        image: redis
        command: ["redis-server"]
        args: ["--requirepass admin123"]
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5
---
