---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: doosra-vpc
spec:
  replicas: 2
  selector:
    matchLabels:
      name: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - name:  web
        image: wancloudsinc/doosra-vpc-backend:latest
        imagePullPolicy: Always
        command: ['/doosra-vpc-be/bin/run_web.sh']
        ports:
        - containerPort: 8081
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: VPCPLUS_LINK
          valueFrom:
            configMapKeyRef:
              name: backend-web-configmap
              key: VPCPLUS_LINK
        - name: GOOGLE_OAUTH_LINK
          valueFrom:
            configMapKeyRef:
              name: backend-web-configmap
              key: GOOGLE_OAUTH_LINK
        - name: RABBIT_ENV_RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: backend-common-configmap
              key: RABBIT_ENV_RABBITMQ_USER
        - name: RABBIT_ENV_RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: backend-common-configmap
              key: RABBIT_ENV_RABBITMQ_PASSWORD
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-common-configmap
              key: REDIS_PORT
        - name: GENERATION
          valueFrom:
            configMapKeyRef:
              name: backend-common-configmap
              key: GENERATION
        - name: FLASK_CONFIG
          valueFrom:
            configMapKeyRef:
              name: backend-common-configmap
              key: FLASK_CONFIG
        - name: SECURE
          valueFrom:
            configMapKeyRef:
              name: backend-common-configmap
              key: SECURE
        - name: WEBDB_ENV_MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: backend-db-secret
              key: WEBDB_ENV_MYSQL_USER
        - name: WEBDB_ENV_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-db-secret
              key: WEBDB_ENV_MYSQL_PASSWORD
        - name: WEBDB_ENV_MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-db-secret
              key: WEBDB_ENV_MYSQL_ROOT_PASSWORD
        - name: WEBDB_ENV_MYSQL_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-common-configmap
              key: WEBDB_ENV_MYSQL_DB_HOST
        - name: WEBDB_ENV_MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: backend-common-configmap
              key: WEBDB_ENV_MYSQL_DATABASE
        - name: SITE
          valueFrom:
            configMapKeyRef:
              name: backend-common-configmap
              key: SITE
        volumeMounts:
          - name: web-logs
            mountPath: /doosra-vpc-be/data/logs/web
      volumes:
        - name: web-logs
          hostPath:
            path: /mnt/gluster/logs/web
      imagePullSecrets:
        - name: docker-hub-secret
---
